Kindergarten/Kindergarten/Controllers/CreativityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kindergarten.Controllers
{
    public class CreativityController : Controller
    {
        //
        // GET: /Creativity/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Kindergarten/Kindergarten/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kindergarten.Models;
using System.IO;

namespace Kindergarten.Controllers
{
    public class NewsController : Controller
    {
        //
        // GET: /News/

        //private 
            NewsContext _db = new NewsContext();
            ImagesContext _dbi = new ImagesContext();

        public int PageSize = 4;
        public ViewResult Index(int page = 1)
        {
            var mostRecentEntries =        // Получает самые последние записи
                (from entry in _db.Entries
                 orderby entry.DateAdded descending
                 select entry).Skip((page - 1) * PageSize).Take(PageSize);
            ViewBag.Entries = mostRecentEntries.ToList(); // Передает записи в представление
    
            NewsListViewModel model = new NewsListViewModel
            {
                Entries = ViewBag.Entries,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = (from entry in _db.Entries select entry).Count()
                },
                Images = (from image in _dbi.Entries
                          where image.Type == "news"
                          select image)
            };
            
        
            //delegate NewsEntry del(int Id);
            //del myDelegate = entry => entry.Id;
            ////int j = myDelegate(5); //j = 25


            //return View(mostRecentEntries.ToList()
            //  .OrderBy(p => p.Id)
            //  .Skip((page - 1) * PageSize)
            //  .Take(PageSize));

            return View(model);
        }

        //public ActionResult Create()
        //{
        //    return View();
        //}

        public ViewResult Create()
        {
            NewsEntry model = null;// new NewsEntry();//new NewsEntry();
            return View(model);
        }

        public ActionResult SuccessCreate()
        {
            return View();
        }

        public ActionResult Change(int Id)
        {
            var mostRecentEntries =        // Получает самые последние записи
                from entry in _db.Entries
                 where entry.Id == Id
                 select entry;
            ViewBag.Entries = mostRecentEntries.ToList(); // Передает записи в представление

            NewsListViewModel model = new NewsListViewModel
            {
                Entries = ViewBag.Entries,
                Images = (from image in _dbi.Entries
                          where image.Type == "news"
                          select image)
            };

            IQueryable<NewsEntry> result = from entry in _db.Entries
                                           where entry.Id == Id
                                           select entry;
            _db.Entries.Remove(result.First());
            _db.SaveChanges();

            return View(model);
        }

        [HttpPost]   // Ограничивает доступ только через HTTP метод POST
        public ActionResult Change(News entry) //Принимает класс в качестве параметра
        {
            ImagesEntry image = new ImagesEntry();
            NewsEntry entry2 = new NewsEntry();

            entry2.Text = entry.Text;
            entry2.Title = entry.Title;

            entry2.DateAdded = DateTime.Now;
            _db.Entries.Add(entry2); // Сохраняет запись гостевой книги
            _db.SaveChanges();

            image.Type = "news";
            image.Feedback = entry2.Id;

            if (entry.upload1 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload1.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload1.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image1 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
                //entry.upload1 = null;
                entry2.Image1 = entry.Image1;
            }

            if (entry.upload2 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload2.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload2.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image2 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
                //entry.upload1 = null;
                entry2.Image1 = entry.Image1;
            }

            if (entry.upload3 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload3.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload3.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image3 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
                //entry.upload1 = null;
                entry2.Image1 = entry.Image1;
            }

            if (entry.upload4 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload4.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload4.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image4 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
                //entry.upload1 = null;
                entry2.Image1 = entry.Image1;
            }

            if (entry.upload5 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload5.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload5.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image5 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
                //entry.upload1 = null;
                entry2.Image1 = entry.Image1;
            }

            if (entry.upload6 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload6.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload6.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image6 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
                //entry.upload1 = null;
                entry2.Image1 = entry.Image1;
            }

            if (entry.upload7 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload7.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload7.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image7 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
                //entry.upload1 = null;
                entry2.Image1 = entry.Image1;
            }

            if (entry.upload8 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload8.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload8.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image8 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
                //entry.upload1 = null;
                entry2.Image1 = entry.Image1;
            }

            if (entry.upload9 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload9.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload9.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image9 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
                //entry.upload1 = null;
                entry2.Image1 = entry.Image1;
            }

            if (entry.upload10 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload10.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload10.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image10 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
                //entry.upload1 = null;
                entry2.Image1 = entry.Image1;
            }

            _dbi.SaveChanges();

            //return Content("New entry successfully added.");
            return RedirectToAction("SuccessCreate"); // Перенаправляет обратно к действию Index

            // связывание данных модели (Model binding)
        }


        public ActionResult Delete(int Id)
        {
            NewsContext _db = new NewsContext();
            IQueryable<NewsEntry> result = from entry in _db.Entries
                         where entry.Id == Id
                         select entry;
            _db.Entries.Remove(result.First());

Kindergarten/Kindergarten/Controllers/PhotoGalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kindergarten.Models;

namespace Kindergarten.Controllers
{
    public class PhotoGalleryController : Controller
    {
        //
        // GET: /PhotoGallery/

        ImagesContext _dbi = new ImagesContext();

        public int PageSize = 4;

        public ActionResult Index(int page = 1)
        {
            //var mostRecentEntries =        // Получает самые последние записи
            //    (from entry in _db.Entries
            //     orderby entry.DateAdded descending
            //     select entry).Skip((page - 1) * PageSize).Take(PageSize);
            //ViewBag.Entries = mostRecentEntries.ToList(); // Передает записи в представление

            NewsListViewModel model = new NewsListViewModel
            {
                //Entries = ViewBag.Entries,
                //PagingInfo = new PagingInfo
                //{
                //    CurrentPage = page,
                //    ItemsPerPage = PageSize,
                //    TotalItems = (from entry in _db.Entries select entry).Count()
                //},
                Images = (from image in _dbi.Entries
                          where image.Type == "photogallery"
                          select image)
            };
            return View(model);
        }

        public ViewResult Create()
        {
            NewsEntry model = null;// new NewsEntry();//new NewsEntry();
            return View(model);
        }

        public ActionResult Delete(int Id)
        {
            ImagesEntry image = new ImagesEntry();
            IQueryable<ImagesEntry> result = from entry in _dbi.Entries
                                           where entry.Id == Id
                                           select entry;
            _dbi.Entries.Remove(result.First());
            _dbi.SaveChanges();
            //return RedirectToAction("Index");
            return View();
        }

        [HttpPost]   // Ограничивает доступ только через HTTP метод POST
        public ActionResult Create(News entry) //Принимает класс в качестве параметра
        {
            ImagesEntry image = new ImagesEntry();

            image.Type = "photogallery";

            if (entry.upload1 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload1.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload1.SaveAs(Server.MapPath("~/Content/Image/PhotoGallery/" + fileName));
                entry.Image1 = image.Image = "Content/Image/PhotoGallery/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
            }

            if (entry.upload2 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload2.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload2.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image2 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
            }

            if (entry.upload3 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload3.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload3.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image3 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
            }

            if (entry.upload4 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload4.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload4.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image4 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
            }

            if (entry.upload5 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload5.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload5.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image5 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
            }

            if (entry.upload6 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload6.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload6.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image6 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
            }

            if (entry.upload7 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload7.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload7.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image7 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
            }

            if (entry.upload8 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload8.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload8.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image8 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
            }

            if (entry.upload9 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload9.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload9.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image9 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
            }

            if (entry.upload10 != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(entry.upload10.FileName);
                // сохраняем файл в папку Files в проекте
                entry.upload10.SaveAs(Server.MapPath("~/Content/Image/News/" + fileName));
                entry.Image10 = image.Image = "Content/Image/News/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
            }

            _dbi.SaveChanges();

            //return Content("New entry successfully added.");
            return RedirectToAction("Index"); // Перенаправляет обратно к действию Index

            // связывание данных модели (Model binding)
        }
    }
}

Kindergarten/Kindergarten/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
    <head> @*Задает импортирование CSS и скриптов*@
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
        <div class="wr">
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("ДОУ Детский сад", "Index", "News")</p> @*Устанавливает заголовок страницы*@
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial") @*Выводит частичное представление*@
                       @* Hello, <span class="username">@Html.Partial("_LogOnPartial")</span>!*@
                    </section>
                    
                </div>

            </div>
            <nav>
                        <ul id="menu">  @*Определяет пункты меню*@
                            <li id="red">@Html.ActionLink("Главная", "Index", "News")</li>
                           @* <li>@Html.ActionLink("О нас", "About", "Home")</li>*@
                            <li class="orange">@Html.ActionLink("О нас", "About", "Home")</li>
                            <li class="yellow">@Html.ActionLink("Документы", "Documents", "Home")</li>
                         @*   <li>@Html.ActionLink("На заметку", "Index", "News")</li>*@
                            <li class="green">@Html.ActionLink("Расписание", "Schedule", "Home")</li>
                          @*  <li>@Html.ActionLink("Наше творчество", "Index", "News")</li>*@
                            <li class="cyan">@Html.ActionLink("Фотогалерея", "Index", "PhotoGallery")</li>
                            <li class="blue">@Html.ActionLink("Контакты", "Contact", "Home")</li>
                            <li class="purple">@Html.ActionLink("Задать вопрос", "Index", "Guestbook")</li>
                            
                        </ul>
                    </nav>
                    </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false) @*Выводит содержимое страницы*@

<section class="content-wrapper main-content clear-fix">
<aside>
    <div id="menu2">
    <ul>
        <li class="l1">@Html.ActionLink("Главная", "Index", "News")</li>
        <li class="l1">@Html.ActionLink("О нас", "About", "Home")</li>
                <ul>
                    <li class="l2">@Html.ActionLink("Общая информация", "GeneralInformation", "Home")</li>
                    <li class="l2">@Html.ActionLink("Коллектив", "Staff", "Home")</li>
                    <li class="l2">@Html.ActionLink("Наши дети", "Index", "Children")</li>
                        <ul>
                           @* <li class="l3">@Html.ActionLink("Гномики", "Gnomiki", "Children")</li>
                            <li class="l3">@Html.ActionLink("Землянички", "Zemlyanichki", "Children")</li>
                            <li class="l3">@Html.ActionLink("Кораблики", "Korabliki", "Children")</li>
                            <li class="l3">@Html.ActionLink("Дружная семейка", "Semeyka", "Children")</li>
                            <li class="l3">@Html.ActionLink("Теремок", "Teremok", "Children")</li>
                            <li class="l3">@Html.ActionLink("Родничок", "Rodnichok", "Children")</li>
                            <li class="l3">@Html.ActionLink("Солнышко", "Solnyshko", "Children")</li>*@
                            <li class="l3">@Html.ActionLink("Гномики", "Group", "Children", new { access = 1 }, null)</li>
                            <li class="l3">@Html.ActionLink("Землянички", "Group", "Children", new { access = 7 }, null)</li>
                            <li class="l3">@Html.ActionLink("Кораблики", "Group", "Children", new { access = 2 }, null)</li>
                            <li class="l3">@Html.ActionLink("Дружная семейка", "Group", "Children", new { access = 4 }, null)</li>
                            <li class="l3">@Html.ActionLink("Теремок", "Group", "Children", new { access = 6 }, null)</li>
                            <li class="l3">@Html.ActionLink("Родничок", "Group", "Children", new { access = 3 }, null)</li>
                            <li class="l3">@Html.ActionLink("Солнышко", "Group", "Children", new { access = 5 }, null)</li>
                            @*<li class="l3">@Html.ActionLink("Группа", "Group", "Children", new { access = 1 }, null )</li>*@
                        </ul>
                     <li class="l2">@Html.ActionLink("Родителям", "ToParents", "Home")</li>
                </ul>
        <li class="l1">@Html.ActionLink("Новости", "Index", "News")</li>
        <li class="l1">@Html.ActionLink("Документы", "Documents", "Home")</li>
        <li class="l1">@Html.ActionLink("На заметку", "Interesting", "Home")</li>
            <ul>
                <li class="l2">@Html.ActionLink("МЧС", "MES", "Home")</li>
                <li class="l2">@Html.ActionLink("Медицинский блок", "Medicine", "Home")</li>
                <li class="l2">@Html.ActionLink("Здоровое питание", "Food", "Home")</li>
                <li class="l2">@Html.ActionLink("Страничка логопеда", "Logoped", "Home")</li>
            </ul>
        <li class="l1">@Html.ActionLink("Расписание", "Schedule", "Home")</li>
        <li class="l1">@Html.ActionLink("Наше творчество", "Index", "Creativity")</li>
        <li class="l1">@Html.ActionLink("Фотогалерея", "Index", "PhotoGallery")</li>
        <li class="l1">@Html.ActionLink("Контакты", "Contact", "Home")</li>
       @* <li class="l1">@Html.ActionLink("Как с нами связаться", "Contact", "Home")</li>*@
        <li class="l1">@Html.ActionLink("Задать вопрос", "Index", "Guestbook")</li>
            
    </ul>
    </div>
</aside>
                @RenderBody()
</section>

        </div>
        <footer>
            <div class="content-wrapper">
                <div @*class="float-left"*@>
                    <p>Copyright &copy; 2014-@DateTime.Now.Year "</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>