Kindergarten/Kindergarten/Controllers/ChildrenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kindergarten.Models;

namespace Kindergarten.Controllers
{
    public class ChildrenController : Controller
    {
        //
        // GET: /Children/

        private GuestbookContext _db = new GuestbookContext();

        public int PageSize = 1;

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Delete(int Id)
        {
            GuestbookContext _db = new GuestbookContext();
            IQueryable<GuestbookEntry> result = from entry in _db.Entries
                                                where entry.Id == Id
                                                select entry;
            _db.Entries.Remove(result.First());
            _db.SaveChanges();
            //return RedirectToAction("Index");
            return View();
        }

        public ActionResult DeleteAnswer(int Id)
        {
            GuestbookContext _db = new GuestbookContext();
            var mostRecentEntries =        // Получает самые последние записи
             from entry in _db.Entries
             where entry.Id == Id
             select entry;
            ViewBag.Entries = mostRecentEntries.ToList();

            GuestbookEntry temp = new GuestbookEntry();
            temp.Id = ViewBag.Entries[0].Id;
            temp.DateAdded = ViewBag.Entries[0].DateAdded;
            temp.Name = ViewBag.Entries[0].Name;
            temp.Message = ViewBag.Entries[0].Message;
            temp.Access = ViewBag.Entries[0].Access;

            _db.Entries.Remove(_db.Entries.Find(temp.Id));
            _db.SaveChanges();
            _db.Entries.Add(temp); // Сохраняет запись гостевой книги
            _db.SaveChanges();
            //return RedirectToAction("Index");
            return RedirectToAction("Index");
        }

        [HttpPost]   // Ограничивает доступ только через HTTP метод POST
        public ActionResult Create(GuestbookEntry entry) //Принимает класс GuestbookEntry в качестве параметра
        {
            entry.DateAdded = DateTime.Now;
            _db.Entries.Add(entry); // Сохраняет запись гостевой книги
            _db.SaveChanges();
            //return Content("Ваш вопрос успешно добавлен.");
            return RedirectToAction("Index"); // Перенаправляет обратно к действию Index

            // связывание данных модели (Model binding)
        }

        public ActionResult Reply(int Id/*, int i*/)
        {
            //var model = from entry in _db.Entries
            //                     where entry.Id == Id
            //                     select entry;
            return View(/*model*/);
        }

        [HttpPost]   // Ограничивает доступ только через HTTP метод POST
        public ActionResult Reply(GuestbookEntry entry)
        {
            entry.DateAdded = _db.Entries.Find(entry.Id).DateAdded;
            entry.Name = _db.Entries.Find(entry.Id).Name;
            entry.Message = _db.Entries.Find(entry.Id).Message;
            entry.Access = _db.Entries.Find(entry.Id).Access;
            _db.Entries.Remove(_db.Entries.Find(entry.Id));
            _db.SaveChanges();
            _db.Entries.Add(entry); // Сохраняет запись гостевой книги
            _db.SaveChanges();
            return RedirectToAction("Index"); // Перенаправляет обратно к действию Index
            //return Content("Ответ на вопрос успешно добавлен.");
        }

        public ActionResult ChangeAnswer(int Id/*, int i*/)
        {
            var mostRecentEntries =        // Получает самые последние записи
              from entry in _db.Entries
              where entry.Id == Id
              select entry;
            ViewBag.Entries = mostRecentEntries.ToList(); // Передает записи в представление
            GuestbookEntry model = new GuestbookEntry
            {
                Id = ViewBag.Entries[0].Id,
                Name = ViewBag.Entries[0].Name,
                Message = ViewBag.Entries[0].Message,
                DateAdded = ViewBag.Entries[0].DateAdded,
                Reply = ViewBag.Entries[0].Reply,
                Access = ViewBag.Entries[0].Access
            };
            //var model = from entry in _db.Entries
            //                     where entry.Id == Id
            //                     select entry;
            return View(model);
        }

        [HttpPost]   // Ограничивает доступ только через HTTP метод POST
        public ActionResult ChangeAnswer(GuestbookEntry entry)
        {
            entry.DateAdded = _db.Entries.Find(entry.Id).DateAdded;
            entry.Name = _db.Entries.Find(entry.Id).Name;
            entry.Message = _db.Entries.Find(entry.Id).Message;
            entry.Access = _db.Entries.Find(entry.Id).Access;
            _db.Entries.Remove(_db.Entries.Find(entry.Id));
            _db.SaveChanges();
            _db.Entries.Add(entry); // Сохраняет запись гостевой книги
            _db.SaveChanges();
            return RedirectToAction("Index"); // Перенаправляет обратно к действию Index
            //return Content("Ответ на вопрос успешно добавлен.");
        }

        public ActionResult ChangeQuestion(int Id/*, int i*/)
        {
            var mostRecentEntries =        // Получает самые последние записи
              from entry in _db.Entries
              where entry.Id == Id
              select entry;
            ViewBag.Entries = mostRecentEntries.ToList(); // Передает записи в представление
            GuestbookEntry model = new GuestbookEntry
            {
                Id = ViewBag.Entries[0].Id,
                Name = ViewBag.Entries[0].Name,
                Message = ViewBag.Entries[0].Message,
                DateAdded = ViewBag.Entries[0].DateAdded,
                Reply = ViewBag.Entries[0].Reply,
                Access = ViewBag.Entries[0].Access
            };
            //var model = from entry in _db.Entries
            //                     where entry.Id == Id
            //                     select entry;
            return View(model);
        }

        [HttpPost]   // Ограничивает доступ только через HTTP метод POST
        public ActionResult ChangeQuestion(GuestbookEntry entry)
        {
            entry.DateAdded = _db.Entries.Find(entry.Id).DateAdded;
            //entry.Name = _db.Entries.Find(entry.Id).Name;
            //entry.Message = _db.Entries.Find(entry.Id).Message;
            entry.Access = _db.Entries.Find(entry.Id).Access;
            entry.Reply = _db.Entries.Find(entry.Id).Reply;
            _db.Entries.Remove(_db.Entries.Find(entry.Id));
            _db.SaveChanges();
            _db.Entries.Add(entry); // Сохраняет запись гостевой книги
            _db.SaveChanges();
            return RedirectToAction("Index"); // Перенаправляет обратно к действию Index
            //return Content("Ответ на вопрос успешно добавлен.");
        }

        public ActionResult Gnomiki(int page = 1)
        {
            var mostRecentEntries =        // Получает самые последние записи
              (from entry in _db.Entries where entry.Access == 1  // только разрешенные к чтению 
               orderby entry.DateAdded descending
               select entry).Skip((page - 1) * PageSize).Take(PageSize);
            ViewBag.Entries = mostRecentEntries.ToList(); // Передает записи в представление


            GuestbookListViewModel model = new GuestbookListViewModel
            {
                Entries = ViewBag.Entries,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = (from entry in _db.Entries where entry.Access == 1 select entry).Count()
                }
            };

            return View(model);
        }

        public ActionResult Korabliki(int page = 1)
        {
            var mostRecentEntries =        // Получает самые последние записи
              (from entry in _db.Entries
               where entry.Access == 2  // только разрешенные к чтению 
               orderby entry.DateAdded descending
               select entry).Skip((page - 1) * PageSize).Take(PageSize);
            ViewBag.Entries = mostRecentEntries.ToList(); // Передает записи в представление


            GuestbookListViewModel model = new GuestbookListViewModel
            {
                Entries = ViewBag.Entries,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = (from entry in _db.Entries where entry.Access == 2 select entry).Count()
                }
            };

            return View(model);
        }

        public ActionResult Rodnichok(int page = 1)
        {
            var mostRecentEntries =        // Получает самые последние записи
              (from entry in _db.Entries
               where entry.Access == 3  // только разрешенные к чтению 
               orderby entry.DateAdded descending
               select entry).Skip((page - 1) * PageSize).Take(PageSize);
            ViewBag.Entries = mostRecentEntries.ToList(); // Передает записи в представление


            GuestbookListViewModel model = new GuestbookListViewModel
            {
                Entries = ViewBag.Entries,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = (from entry in _db.Entries where entry.Access == 3 select entry).Count()
                }
            };

            return View(model);
        }

        public ActionResult Semeyka(int page = 1)
        {
            var mostRecentEntries =        // Получает самые последние записи
              (from entry in _db.Entries

Kindergarten/Kindergarten/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kindergarten.Models;

namespace Kindergarten.Controllers
{
    public class HomeController : Controller
    {

        private NewsContext _db = new NewsContext();
        ImagesContext _dbi = new ImagesContext();

        [HttpPost] // загрузка файлов
        public ActionResult Upload(HttpPostedFileBase upload)
        {
            ImagesEntry image = new ImagesEntry();
            if (upload != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(upload.FileName);
                // сохраняем файл в папку Files в проекте
                upload.SaveAs(Server.MapPath("~/Files/" + fileName));

                image.Type = "documents";
                image.Text = fileName;
                image.Image = "Files/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost] // загрузка файлов
        public ActionResult UploadSchedule(HttpPostedFileBase upload)
        {
            ImagesEntry image = new ImagesEntry();
            if (upload != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(upload.FileName);
                // сохраняем файл в папку Files в проекте
                upload.SaveAs(Server.MapPath("~/Files/" + fileName));

                image.Type = "schedule";
                image.Text = fileName;
                image.Image = "Files/" + fileName;
                _dbi.Entries.Add(image);
                _dbi.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int Id)
        {
            //NewsContext _db = new NewsContext();
            IQueryable<ImagesEntry> result = from entry in _dbi.Entries
                                           where entry.Id == Id
                                           select entry;
            _dbi.Entries.Remove(result.First());
            _dbi.SaveChanges();
            //return RedirectToAction("Index");
            return View();
        }

        public ActionResult Index()
        {
            ViewBag.Message = "Измените этот шаблон, чтобы быстро приступить к работе над приложением ASP.NET MVC.";


            var mostRecentEntries =        // Получает самые последние записи
             (from entry in _db.Entries
              orderby entry.DateAdded descending
              select entry).Take(20);
            ViewBag.Entries = mostRecentEntries.ToList(); // Передает записи в представление

            return View();
        }


        public ActionResult About()
        {
            ViewBag.Message = "Страница описания приложения.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Страница контактов.";

            return View();
        }

        public ActionResult Schedule()
        {
            ViewBag.Message = "Расписание занятий.";

            NewsListViewModel model = new NewsListViewModel
            {
                Entries = ViewBag.Entries,
                Images = (from image in _dbi.Entries
                          where image.Type == "schedule"
                          select image)
            };

            return View(model);
        }

        public ActionResult Interesting()
        {
            ViewBag.Message = "На заметку.";

            return View();
        }

        public ActionResult MES()
        {
            ViewBag.Message = "МЧС.";

            return View();
        }

        public ActionResult Medicine()
        {
            ViewBag.Message = "Медицинский блок.";

            return View();
        }

        public ActionResult Food()
        {
            ViewBag.Message = "Здоровое питание.";

            return View();
        }

        public ActionResult Logoped()
        {
            ViewBag.Message = "Страничка логопеда.";

            return View();
        }

        public ActionResult GeneralInformation()
        {
            ViewBag.Message = "Общая информация.";

            return View();
        }

        public ActionResult Staff()
        {
            ViewBag.Message = "Общая информация.";

            return View();
        }

        public ActionResult ToParents()
        {
            ViewBag.Message = "Общая информация.";

            return View();
        }

        public ActionResult Documents()
        {
            ViewBag.Message = "Общая информация.";

            NewsListViewModel model = new NewsListViewModel
            {
                Entries = ViewBag.Entries,
                Images = (from image in _dbi.Entries
                          where image.Type == "documents"
                          select image)
            };

            return View(model);
        }


    }
}

Kindergarten/Kindergarten/Views/Home/About.cshtml
@{
    ViewBag.Title = "О нас";
}
<b>

    <h2>О нас</h2>
<br><br>
<ul>
                    <li>@Html.ActionLink("Общая информация", "GeneralInformation", "Home")</li>
                    <li>@Html.ActionLink("Коллектив", "Staff", "Home")</li>
                    <li>@Html.ActionLink("Наши дети", "Index", "Children")</li>
                    <li>@Html.ActionLink("Родителям", "ToParents", "Home")</li>
                </ul>

Kindergarten/Kindergarten/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Контакты";
}


<br>
<hgroup class="title">
   @* <h1>@ViewBag.Title.</h1>*@
    <h2>Как с нами связаться?@*@ViewBag.Message*@</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Заведующая</h3>
    </header>
    <p>
        ФИО
    </p>
</section>

<section class="contact">
    <header>
        <h3>Телефон</h3>
    </header>
    <p>
        @*<span class="label">Основной:</span>*@
        <span>777777777</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Адрес электронной почты</h3>
    </header>
    <p>
        77777@mail.ru
    </p>
</section>

<section class="contact">
    <header>
        <h3>Адрес</h3>
    </header>
    <p>
        Россия, Новосибирск
    </p>
</section>
<br>

    @*<header>
        <h3>Телефон:</h3>
    </header>
    <p>
        <span class="label">Основной:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">Нерабочее время:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Адрес электронной почты</h3>
    </header>
    <p>
        <span class="label">Поддержка:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Маркетинг:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">Общие вопросы:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Адрес</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>*@

@*<aside>
    <h3>Заголовок боковой панели</h3>
    <p>
        В этой области можно указать дополнительные сведения.
    </p>
    <ul>
        <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
        <li>@Html.ActionLink("О программе", "About", "Home")</li>
        <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
    </ul>
</aside>*@

Kindergarten/Kindergarten/Views/Home/Delete.cshtml
@{
    ViewBag.Title = "Ваш окумент успешно удален!";
}

@*<h2>Delete</h2>*@
<br> <br> <br> <br> 
<b> Документ успешно удален! </b>

<br> <br> 

@Html.ActionLink("К документам", "Documents", "Home")

Kindergarten/Kindergarten/Views/Home/Food.cshtml
@{
    ViewBag.Title = "Здоровое питание";
}
<br>
<h2>Здоровое питание</h2>
<br><br>
<img src="../Content/Documents/Food/food1.JPG" width="650"/>
@*<img src="../Content/Documents/Food/food2.JPG" width="650"/>*@
<br><br>
<h3>Рекомендуем ознакомиться:</h3>
<ul>
    <li type="circle"><a href="../Content/Documents/Food/О правильном питании.docx">О правильном питании</a></li>
    <li type="circle"><a href="../Content/Documents/Food/Объем порций.docx">Объем порций</a></li>
    <li type="circle"><a href="../Content/Documents/Food/График получения пищи.docx">График получения пищи</a></li>
</ul>
<br><br><br>

Kindergarten/Kindergarten/Views/Home/GeneralInformation.cshtml
@{
    ViewBag.Title = "Общая информация";
}
<br>
<h2>Общая информация</h2>
<br><br>

<p>Дошкольное образовательное учреждение детский сад .</p>
<p>Наше кредо: «Любовь к детям воспитывается только любовью, как огонь зажигается только от огня». (В.А. Сухомлинский)</p>
<br><br>
<b>Адрес:</b> г. Новосибирск<br>
<b>Телефон:</b> <br>
<b>Факс:</b> <br>
<b>E-mail:</b> 777@mail.ru<br>
<b>Заведующая:</b> .
<br><br>

<h3>Режим работы ДОУ</h3>

Режим 5-дневной учебной недели, выходные дни – суббота и воскресенье.<br> 
Режим работы учреждения и длительность пребывания в нем детей определяются Положением ДОО, функционирует в 12-часовом режиме дня, с 7 часов 30 минут до 19 часов 00 минут.<br>
<br>
Образовательный процесс строится следующим образом:
<li>с 1 сентября по 30 мая – образовательный период;</li>
<li>с 1 июня по 31 июня – летний оздоровительный период;</li>
<li>с 1 января по 11 января – каникулы.</li>
<br><br><br>

Kindergarten/Kindergarten/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная страница";
}

<h2 align="center">Последние новости</h2>

     <hr></hr>

 @*<section class="contact">*@

@* <aside>
    <div id="menu">
    <ul>
        <li>@Html.ActionLink("Главная", "Index", "Home")</li>
        <li>@Html.ActionLink("О нас", "About", "Home")</li>
                <ul>
                    <li>@Html.ActionLink("Общая информация", "", "")</li>
                    <li>@Html.ActionLink("Коллектив", "", "")</li>
                    <li>@Html.ActionLink("Наши дети", "", "")</li>
                        <ul>
                            <li>@Html.ActionLink("Гномики", "", "")</li>
                            <li>@Html.ActionLink("Землянички", "", "")</li>
                            <li>@Html.ActionLink("Кораблики", "", "")</li>
                            <li>@Html.ActionLink("Дружная семейка", "", "")</li>
                            <li>@Html.ActionLink("Теремок", "", "")</li>
                            <li>@Html.ActionLink("Родничок", "", "")</li>
                            <li>@Html.ActionLink("Солнышко", "", "")</li>
                        </ul>
                     <li>@Html.ActionLink("Родителям", "", "")</li>
                </ul>
        <li>@Html.ActionLink("Новости", "", "")</li>
        <li>@Html.ActionLink("Документы", "", "")</li>
        <li>@Html.ActionLink("На заметку", "Interesting", "Home")</li>
            <ul>
                <li>@Html.ActionLink("МЧС", "MES", "Home")</li>
                <li>@Html.ActionLink("Медицинский блок", "Medicine", "Home")</li>
                <li>@Html.ActionLink("Здоровое питание", "Food", "Home")</li>
                <li>@Html.ActionLink("Страничка логопеда", "Logoped", "Home")</li>
            </ul>
        <li>@Html.ActionLink("Расписание", "", "")</li>
        <li>@Html.ActionLink("Наше творчество", "", "")</li>
        <li>@Html.ActionLink("Фотогалерея", "", "")</li>
        <li>@Html.ActionLink("Контакты", "", "")</li>
            <ul>
                <li>@Html.ActionLink("Как с нами связаться", "", "")</li>
                <li>@Html.ActionLink("Задать вопрос", "", "")</li>
            </ul>
    </ul>
    <div>
</aside>*@
@*</section>*@

@*<aside>
<div id="menu">
    <ul>
        <li><a href="">Главная</a></li>
        <li><a href="">О компании</a>
            <ul>
                <li><a href="">Производство</a></li>
                <li><a href="">Клиенты</a></li>
                <li><a href="">Для партнеров</a></li>
                <li><a href="">Для клиентов</a></li>
                <li><a href="">Реклама</a></li>
            </ul>
        </li>
        <li><a href="">Услуги</a></li>
    </ul>
    <div style="clear: both;"></div>
</div>
</aside>*@


@foreach (var entry in ViewBag.Entries) 
{
    
<section class="contact">
      
      <p align="right">@entry.DateAdded.ToLongDateString() @entry.DateAdded.ToString("hh:mm")</p>
      <h3>&nbsp; &nbsp; &nbsp;@entry.Title</h3>
      <p>@entry.Text</p>
      <hr></hr>
  </section>

}

Kindergarten/Kindergarten/Views/Home/Interesting.cshtml
@{
    ViewBag.Title = "На заметку";
}
<br>
<h2>На заметку</h2>


<ul>
    <li>@Html.ActionLink("МЧС", "MES", "Home")</li>
    <li>@Html.ActionLink("Медицинский блок", "Medicine", "Home")</li>
    <li>@Html.ActionLink("Здоровое питание", "Food", "Home")</li>
    <li>@Html.ActionLink("Страничка логопеда", "Logoped", "Home")</li>
</ul>
<br>
<br>
<br>

Kindergarten/Kindergarten/Views/Home/Logoped.cshtml
@{
    ViewBag.Title = "Логопед";
}
<br>
<h2>Логопед</h2>
<br><br>
Наш логопед.<br><br>
В детском саду «Веснушки» работает логопедический кабинет или логопункт. Это означает, что из различных групп набираются дети, которым необходима помощь логопеда и с ними занимаются профессиональные педагоги. Логопеды оказывают помощь детям, возраст которых составляет от 4,5 до 7 лет и у которых имеются фонематические, фонетико-фонематические, фонетические и общие нарушения речи. <br>
В логопункте с воспитанниками, имеющими нарушения речи, проводится квалифицированная профилактическая и коррекционно-воспитательная работа с учетом возможностей и общего психофизического детей.<br>
В логопедический пункт дети попадают после диагностики и решения медико-педагогической комиссии. Поэтому коррекционно-развивающие занятия не входят в учебный план. Занятия, проводимые логопедами помогают выявлению и последующему устранению нарушений речи, формированию правильного произношения и развитию навыков связной речи.
<br><br>
<br><br>
<h3>Рекомендуем ознакомиться:</h3>
<ul>
    <li type="circle"><a href="../Content/Documents/Logoped/Развитие речи. Звукопроизношение.docx">Развитие речи. Звукопроизношение</a></li>
</ul>

Kindergarten/Kindergarten/Views/Home/Schedule.cshtml
@model Kindergarten.Models.NewsListViewModel

@{
    ViewBag.Title = "Расписание";
}

<h2>Расписание образовательной деятельности в д/с на 2014-2015 уч. год</h2>

@*<iframe src="../Content/Расписание.docx">*@
<ul>
</ul>
<br><br><br>

@foreach (var image in Model.Images)
{    
    <li type="circle"><a href="../@image.Image">@image.Text</a></li>   
    if (User.Identity.Name == "Administrator")
    {  
         @Html.ActionLink("Удалить", "Delete", new { id = image.Id })
    }
}

@if (User.Identity.Name == "Administrator")
{
    {
        ViewBag.Title = "Upload";
    }
<h3>Выберите файл для загрузки</h3>
    using (Html.BeginForm("UploadSchedule", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
    <input type="file" name="upload" /><br>
    <input type="submit" value="Загрузить" />
}
}

Kindergarten/Kindergarten/Views/Home/Staff.cshtml
@{
    ViewBag.Title = "Наш коллектив";
}
<br>
<h2>Наш коллектив</h2>
<br><br>
<br><br>



<br><br>

Kindergarten/Kindergarten/Views/Home/ToParents.cshtml
@{
    ViewBag.Title = "Родителям";
}
<br>
<h2>Родителям</h2>
<br><br>
<img src="../Content/Documents/ToParents/parents1.JPG" width="650"/>
<br><br>
Ст. 18 Закон Российской Федерации «Об Образовании». «Родители являются первыми педагогами. Они обязаны заложить основы физического и интеллектуального развития личности ребенка».

<br><br>
<p><b>ЗАПОВЕДИ ВОСПИТАНИЯ:</b></p>
<ol>
 <li><b>Люби своего ребенка!</b><br>
То есть радуйся его присутствию, принимай его таким, каков он есть, не оскорбляй его, не унижай его, не подрывай его уверенности в себе, не подвергай его несправедливому наказанию, дай повод любить тебя.</li>
 <li><b>Охраняй своего ребенка!</b><br>
То есть защищай его от физических и душевных опасностей, даже жертвуя собственными интересами, а иногда жизнью.</li>
 <li><b>Будь добрым примером для своего ребенка!</b><br>
Ребенку необходим такой домашний очаг, где семья дружна, где уважают и любят стариков, где поддерживаются тесные и искренние связи со всеми родственниками и друзьями. Ребенок должен жить в честной, скромной, гармоничной семье.</li>
 <li><b>Играй со своим ребенком!</b><br>
Уделяй ему необходимое время, разговаривай с ним, играй с ним так, как ему нравится, игры его принимай всерьез, освойся с миром его представлений.</li>
 <li><b>Трудись со своим ребенком!</b><br>
Помогай ребенку, когда он пытается принять участие в работе – дома, в саду или огороде. Когда ребенок подрастет, приучай его участвовать во всех работах по хозяйству.</li>
 <li><b>Позволь ребенку приобретать жизненный опыт, пусть даже не безболезненно, но самостоятельно!</b><br>
Ребенок признает только такой опыт, который он пережил самолично. Дай ему возможность накопить собственный опыт, даже если это связано с известным риском.</li>
 <li><b>Покажи ребенку возможности и пределы человеческой свободы!</b><br>
Родители должны раскрыть перед ребенком замечательные возможности развития и утверждения человеческой личности, соответственно дарованиям и особенностям каждого. </li>
 <li><b>Приучай ребенка быть послушным!</b><br>
Родители обязаны следить за поведением ребенка и направлять таким образом, чтобы его поступки не причиняли ущерба ни себе, ни другим. </li>
 <li><b>Жди от ребенка только таких мнений и оценок, на какие он способен в соответствии со ступенью созревания и собственным опытом!</b><br>
Ребенку требуется длительное время, чтобы научится ориентироваться в этом мире. Помогай ему, сколько сможешь.</li>
 <li><b>Предоставляй ребенку возможность таких переживаний, которые будут иметь ценность воспоминаний!</b></li>

</ol>
<br><br>
<h3>Рекомендуем ознакомиться:</h3>
<ul>
    <li type="circle"><a href="../Content/Documents/ToParents/Советы родителям.docx">Советы родителям</a></li>
    <li type="circle"><a href="../Content/Documents/ToParents/Конвенция о правах ребенка.docx">Конвенция о правах ребенка</a></li>
    <li type="circle"><a href="../Content/Documents/ToParents/Правила катания на самокате и велосипеде.docx">Правила катания на самокате и велосипеде</a></li>
    <li type="circle"><a href="../Content/Documents/ToParents/Зачем ребенку кукольный театр.docx">Зачем ребенку кукольный театр?</a></li>
</ul>
<br><br><br>

Kindergarten/Kindergarten/Views/Home/Upload.cshtml
@{
    ViewBag.Title = "Upload";
}

<h2>Upload</h2>