Kindergarten/Kindergarten/Controllers/GuestbookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kindergarten.Models;

namespace Kindergarten.Controllers
{
    public class GuestbookController : Controller
    {
        //
        // GET: /Guestbook/

        private GuestbookContext _db = new GuestbookContext();

        public int PageSize = 1;
        public ActionResult Index(int page = 1)
        {
            var mostRecentEntries =        // Получает самые последние записи
              (from entry in _db.Entries where entry.Access == 0
               orderby entry.DateAdded descending
               select entry).Skip((page - 1) * PageSize).Take(PageSize);
            ViewBag.Entries = mostRecentEntries.ToList(); // Передает записи в представление
            

            GuestbookListViewModel model = new GuestbookListViewModel
            {
                Entries = ViewBag.Entries,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = (from entry in _db.Entries where entry.Access == 0 select entry).Count()
                }
            };

            return View(model);
        }

        public ActionResult Delete(int Id)
        {
            GuestbookContext _db = new GuestbookContext();
            IQueryable<GuestbookEntry> result = from entry in _db.Entries
                                           where entry.Id == Id
                                           select entry;
            _db.Entries.Remove(result.First());
            _db.SaveChanges();
            //return RedirectToAction("Index");
            return View();
        }

        public ActionResult DeleteAnswer(int Id)
        {
            GuestbookContext _db = new GuestbookContext();
            var mostRecentEntries =        // Получает самые последние записи
             from entry in _db.Entries
             where entry.Id == Id
             select entry;
            ViewBag.Entries = mostRecentEntries.ToList();

            GuestbookEntry temp = new GuestbookEntry();
            temp.Id = ViewBag.Entries[0].Id;
            temp.DateAdded = ViewBag.Entries[0].DateAdded;
            temp.Name = ViewBag.Entries[0].Name;
            temp.Message = ViewBag.Entries[0].Message;
            temp.Access = ViewBag.Entries[0].Access;

            _db.Entries.Remove(_db.Entries.Find(temp.Id));
            _db.SaveChanges();
            _db.Entries.Add(temp); // Сохраняет запись гостевой книги
            _db.SaveChanges();
            //return RedirectToAction("Index");
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult ChangeAnswer(int Id/*, int i*/)
        {
            var mostRecentEntries =        // Получает самые последние записи
              from entry in _db.Entries
              where entry.Id == Id
              select entry;
            ViewBag.Entries = mostRecentEntries.ToList(); // Передает записи в представление
            GuestbookEntry model = new GuestbookEntry
            {
                Id = ViewBag.Entries[0].Id,
                Name = ViewBag.Entries[0].Name,
                Message = ViewBag.Entries[0].Message,
                DateAdded = ViewBag.Entries[0].DateAdded,
                Reply = ViewBag.Entries[0].Reply,
                Access = ViewBag.Entries[0].Access
            };
            //var model = from entry in _db.Entries
            //                     where entry.Id == Id
            //                     select entry;
            return View(model);
        }

        [HttpPost]   // Ограничивает доступ только через HTTP метод POST
        public ActionResult ChangeAnswer(GuestbookEntry entry)
        {
            entry.DateAdded = _db.Entries.Find(entry.Id).DateAdded;
            entry.Name = _db.Entries.Find(entry.Id).Name;
            entry.Message = _db.Entries.Find(entry.Id).Message;
            entry.Access = _db.Entries.Find(entry.Id).Access;
            _db.Entries.Remove(_db.Entries.Find(entry.Id));
            _db.SaveChanges();
            _db.Entries.Add(entry); // Сохраняет запись гостевой книги
            _db.SaveChanges();
            return RedirectToAction("Index"); // Перенаправляет обратно к действию Index
            //return Content("Ответ на вопрос успешно добавлен.");
        }

        public ActionResult ChangeQuestion(int Id/*, int i*/)
        {
            var mostRecentEntries =        // Получает самые последние записи
              from entry in _db.Entries where entry.Id == Id
               select entry;
            ViewBag.Entries = mostRecentEntries.ToList(); // Передает записи в представление
            GuestbookEntry model = new GuestbookEntry
            {
                Id = ViewBag.Entries[0].Id,
                Name = ViewBag.Entries[0].Name,
                Message = ViewBag.Entries[0].Message,
                DateAdded = ViewBag.Entries[0].DateAdded,
                Reply = ViewBag.Entries[0].Reply,
                Access = ViewBag.Entries[0].Access
            };
            //var model = from entry in _db.Entries
            //                     where entry.Id == Id
            //                     select entry;
            return View(model);
        }

        [HttpPost]   // Ограничивает доступ только через HTTP метод POST
        public ActionResult ChangeQuestion(GuestbookEntry entry)
        {
            entry.DateAdded = _db.Entries.Find(entry.Id).DateAdded;
            //entry.Name = _db.Entries.Find(entry.Id).Name;
            //entry.Message = _db.Entries.Find(entry.Id).Message;
            entry.Access = _db.Entries.Find(entry.Id).Access;
            entry.Reply = _db.Entries.Find(entry.Id).Reply;
            _db.Entries.Remove(_db.Entries.Find(entry.Id));
            _db.SaveChanges();
            _db.Entries.Add(entry); // Сохраняет запись гостевой книги
            _db.SaveChanges();
            return RedirectToAction("Index"); // Перенаправляет обратно к действию Index
            //return Content("Ответ на вопрос успешно добавлен.");
        }

        public ActionResult Reply(int Id/*, int i*/)
        {
            //var model = from entry in _db.Entries
            //                     where entry.Id == Id
            //                     select entry;
            return View(/*model*/);
        }

        [HttpPost]   // Ограничивает доступ только через HTTP метод POST
        public ActionResult Reply(GuestbookEntry entry)
        {
            entry.DateAdded = _db.Entries.Find(entry.Id).DateAdded;
            entry.Name = _db.Entries.Find(entry.Id).Name;
            entry.Message = _db.Entries.Find(entry.Id).Message;
            entry.Access = _db.Entries.Find(entry.Id).Access;
            _db.Entries.Remove(_db.Entries.Find(entry.Id));
            _db.SaveChanges();
            _db.Entries.Add(entry); // Сохраняет запись гостевой книги
            _db.SaveChanges();
            return RedirectToAction("Index"); // Перенаправляет обратно к действию Index
            //return Content("Ответ на вопрос успешно добавлен.");
        }

        //public ViewResult Show(int id)
        //{
        //    var entry = _db.Entries.Find(id);
        //    bool hasPermission = User.Identity.Name == entry.Name;
        //    ViewData["hasPermission"] = hasPermission;
        //    //ViewBag.HasPermission = hasPermission;
        //    return View(entry);
        //}

        [HttpPost]   // Ограничивает доступ только через HTTP метод POST
        public ActionResult Create(GuestbookEntry entry) //Принимает класс GuestbookEntry в качестве параметра
        {
            entry.DateAdded = DateTime.Now;
            _db.Entries.Add(entry); // Сохраняет запись гостевой книги
            _db.SaveChanges();
            //return Content("Ваш вопрос успешно добавлен.");
            return RedirectToAction("Index"); // Перенаправляет обратно к действию Index

           // связывание данных модели (Model binding)
        }
    }
}

Kindergarten/Kindergarten/Views/Guestbook/ChangeAnswer.cshtml
@model Kindergarten.Models.GuestbookEntry

@{
    ViewBag.Title = "ChangeAnswer";
}

<h2>Редактирование ответа</h2>

<form method="post">
  <fieldset>
    <br />
   @* Имя спрашивающего:
    <br />
    <input type="text" name="Name" maxlength="200" value = @Model.Name />
    <br />*@
    <br />
    Текст ответа:
    <br />
    <textarea name="Reply" rows="10" cols="40" @*placeholder =*@  />@Model.Reply
    </textarea>
    @*<input type="text" name="Message" maxlength="400" @*value="model.Message"/>*@
@*    <br />
    <br />
    Текст ответа:
    <br />
    <textarea name="Reply" rows="10" cols="40">
    </textarea>*@
    <br />
    <br />
    <input type="submit" value="Сохранить" />
  </fieldset>
</form>

Kindergarten/Kindergarten/Views/Guestbook/ChangeQuestion.cshtml
@model Kindergarten.Models.GuestbookEntry

@{
    ViewBag.Title = "ChangeQuestion";
}

<h2>Редактирование вопроса</h2>

<form method="post">
  <fieldset>
    <br />
    Имя спрашивающего:
    <br />
    <input type="text" name="Name" maxlength="200" value = @Model.Name />
    <br />
    <br />
    Текст вопроса:
    <br />
    <textarea name="Message" rows="10" cols="40" @*placeholder =*@  />@Model.Message
    </textarea>
    @*<input type="text" name="Message" maxlength="400" @*value="model.Message"/>*@
@*    <br />
    <br />
    Текст ответа:
    <br />
    <textarea name="Reply" rows="10" cols="40">
    </textarea>*@
    <br />
    <br />
    <input type="submit" value="Сохранить" />
  </fieldset>
</form>

Kindergarten/Kindergarten/Views/Guestbook/Create.cshtml
@{
    ViewBag.Title = "Задать вопрос";
}

<h2>Есть вопрос? Есть ответ!</h2>

<form method="post" action="">
  <fieldset>
    <br />
    Представьтесь, пожалуйста:
    <br />
    <input type="text" name="Name" maxlength="200" />
    <br />
    <br />
    Введите, пожалуйста, текст Вашего сообщения:
    <br />
    <textarea name="Message" rows="10" cols="40">
    </textarea>
    <br />
    <br />
    <input type="submit" value="Задать вопрос" />
  </fieldset>
</form>

Kindergarten/Kindergarten/Views/Guestbook/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

@*<h2>Delete</h2>*@

<br> <br> <br> <br> 
<b> Вопрос успешно удален! </b>

<br> <br> 

@Html.ActionLink("К вопросам", "Index", "Guestbook")

Kindergarten/Kindergarten/Views/Guestbook/Index.cshtml
@*@using Guestbook.Models
@model List<GuestbookEntry>*@
@model Kindergarten.Models.GuestbookListViewModel

@{
    ViewBag.Title = "Вопрос - ответ";
}


<h2 align="center">Вопрос - ответ</h2>

<p>
 @* <a href="/Guestbook/Create">Задать вопрос</a>*@
  @Html.ActionLink("Задать вопрос", "Create", new { Access = 0 })
</p>
<br>
<hr></hr>

@foreach (var entry in Model.Entries) 
{
  <section class="contact">     
      <b><p align="right">@entry.DateAdded.ToLongDateString() @entry.DateAdded.ToString("hh:mm")</p></b>
      <h3>&nbsp; &nbsp; &nbsp;@entry.Name</h3>
      <i>Вопрос:</i>
      <p>@entry.Message</p>
      <br>
       @if (User.Identity.Name == "Administrator")
       {
           @Html.ActionLink("Редактировать вопрос", "ChangeQuestion", new { id = entry.Id })
           <i>|</i>
           @Html.ActionLink("Удалить вопрос", "Delete", new { id = entry.Id })
       }
        <br>
         <br>
       @if (entry.Reply != null)
       { 
      <i>Ответ:</i>
      <p>@entry.Reply</p>
      <br>
       }
      @if (User.Identity.Name == "Administrator")
      {
          if (entry.Reply == null)
          { 
            @Html.ActionLink("Ответить", "Reply", new { id = entry.Id, i = entry.Id })
          }

          if (entry.Reply != null)
          { 
            @Html.ActionLink("Изменить ответ", "ChangeAnswer", new { id = entry.Id, i = entry.Id })
            <i>|</i>
            @Html.ActionLink("Удалить ответ", "DeleteAnswer", new { id = entry.Id, i = entry.Id })
          }
      }
      <hr></hr>
  </section>
}
<div class="pager">
  @Html.PageLinks(Model.PagingInfo, x => Url.Action("Index", new { page = x }))
</div>
    

Kindergarten/Kindergarten/Views/Guestbook/Reply.cshtml
@model Kindergarten.Models.GuestbookEntry

@{
    ViewBag.Title = "Reply";
}

<h2>Режим ответа на вопрос</h2>

<form method="post">
  <fieldset>
    @*<br />
    Имя спрашивающего:
    <br />
    <input type="text" name="Name" maxlength="200" @*value="model.Name" />*@
    @*<br />
    <br />
    Текст вопроса:
    <br />*@
   @* <textarea name="Message" rows="10" cols="40" placeholder="model.Message">
    </textarea>*@
    @*<input type="text" name="Message" maxlength="400" @*value="model.Message"/>*@
    <br />
    <br />
    Текст ответа:
    <br />
    <textarea name="Reply" rows="10" cols="40">
    </textarea>
    <br />
    <br />
    <input type="submit" value="Ответить" />
  </fieldset>
</form>

Kindergarten/Kindergarten/Views/Guestbook/Show.cshtml
@{
    ViewBag.Title = "Show";
}


<h2>Guestbook Entry</h2>
<dl>
  <dt>Name:</dt>
  <dd>@Model.Name</dd>
  <dt>Date Added:</dt>
  <dd>@Model.DateAdded</dd>
  <dt>Message:</dt>
  <dd>@Model.Message</dd>
</dl>


<p>
  @{
    bool hasPermission =
      (bool) ViewData["hasPermission"];
  }
  @if (hasPermission)
  {
    @Html.ActionLink("Edit", "Edit", new {id = Model.Id})
  }
  @Html.ActionLink("Back to Entries", "Index")
</p>

@*<p>
  @if (ViewBag.HasPermission)
  {
    @Html.ActionLink("Edit", "Edit", new {id = Model.Id})
  }
  @Html.ActionLink("Back to Entries", "Index")
</p>*@